# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class mainform(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(877, 690)
        Form.tableWidget = QtWidgets.QTableWidget(Form)
        Form.tableWidget.setGeometry(QtCore.QRect(0, 0, 881, 691))
        Form.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        Form.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        Form.tableWidget.setTabKeyNavigation(True)
        Form.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        Form.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        Form.tableWidget.setShowGrid(True)
        Form.tableWidget.setCornerButtonEnabled(False)
        Form.tableWidget.setObjectName("tableWidget")
        Form.tableWidget.setColumnCount(7)
        Form.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        Form.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        Form.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        Form.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        Form.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        Form.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        Form.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        Form.tableWidget.setHorizontalHeaderItem(6, item)
        Form.tableWidget.horizontalHeader().setVisible(True)
        Form.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        Form.tableWidget.horizontalHeader().setDefaultSectionSize(125)
        Form.tableWidget.horizontalHeader().setStretchLastSection(True)
        Form.tableWidget.verticalHeader().setVisible(False)
        Form.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        Form.tableWidget.verticalHeader().setHighlightSections(True)
        Form.tableWidget.verticalHeader().setMinimumSectionSize(30)
        Form.tableWidget.verticalHeader().setStretchLastSection(False)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = Form.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = Form.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "название сорта"))
        item = Form.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Степень обжарки"))
        item = Form.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Тип"))
        item = Form.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Описание вкуса"))
        item = Form.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Цена"))
        item = Form.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Объем упаковки"))

